--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-17-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ZIPCODE
--------------------------------------------------------

  CREATE TABLE "SCOTT"."ZIPCODE" 
   (	"ZIPCODE" VARCHAR2(5 BYTE), 
	"SIDOK" VARCHAR2(30 BYTE), 
	"SIDOE" VARCHAR2(40 BYTE), 
	"SIGUNGUK" VARCHAR2(30 BYTE), 
	"SIGUNGUE" VARCHAR2(40 BYTE), 
	"UPMYENK" VARCHAR2(20 BYTE), 
	"UPMYENE" VARCHAR2(40 BYTE), 
	"DORO_CODE" VARCHAR2(12 BYTE), 
	"DOROK" VARCHAR2(80 BYTE), 
	"DOROE" VARCHAR2(80 BYTE), 
	"JIHA_FLAG" VARCHAR2(1 BYTE), 
	"BD_NUM1" NUMBER(5,0), 
	"BD_NUM2" NUMBER(5,0), 
	"BD_MNG_NUM" VARCHAR2(25 BYTE), 
	"MULTI_NAME" VARCHAR2(40 BYTE), 
	"BD_NAME" VARCHAR2(200 BYTE), 
	"LAW_CODE" VARCHAR2(10 BYTE), 
	"LAW_NAME" VARCHAR2(20 BYTE), 
	"RI_NAME" VARCHAR2(20 BYTE), 
	"ADMIN_DONG" VARCHAR2(40 BYTE), 
	"SAN_FLAG" VARCHAR2(1 BYTE), 
	"JIBEON1" NUMBER(4,0), 
	"UMD_SEQ" VARCHAR2(2 BYTE), 
	"JIBEON2" NUMBER(4,0), 
	"OLD_ZIP" VARCHAR2(6 BYTE), 
	"OLD_SEQ" VARCHAR2(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KOSMO41" ;
--------------------------------------------------------
--  Constraints for Table ZIPCODE
--------------------------------------------------------

  ALTER TABLE "SCOTT"."ZIPCODE" MODIFY ("UMD_SEQ" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ZIPCODE" MODIFY ("DORO_CODE" NOT NULL ENABLE);
  ALTER TABLE "SCOTT"."ZIPCODE" MODIFY ("ZIPCODE" NOT NULL ENABLE);
