/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.33
 * Generated at: 2018-08-24 09:02:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;

public final class A05Modify_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	Connection con;
	Statement stmt;
	ResultSet resultSet;
	
	String driver = "oracle.jdbc.driver.OracleDriver";
	String url = "jdbc:oracle:thin:@localhost:1521:xe";
	String uid = "scott";
	String upw = "tiger";
	String query = "select * from member";
	
	String name, id, pw, phone1, phone2, phone3, gender;

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.Connection");
    _jspx_imports_classes.add("java.sql.ResultSet");
    _jspx_imports_classes.add("java.sql.Statement");
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery.js\"></script>\r\n");
      out.write("<title>수정페이지</title>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar queryString;\r\n");
      out.write("\r\n");
      out.write("\tfunction form_check() {\r\n");
      out.write("\t\tqueryString = $('#ModifyProcess').serialize();\r\n");
      out.write("\r\n");
      out.write("\t\talert(queryString);\r\n");
      out.write("\t\tsubmit_ajax();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction submit_ajax() {\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '/Jsp19_2/ModifyProcess',\r\n");
      out.write("\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\tdata : queryString,\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\tsuccess : function(json) {\r\n");
      out.write("\t\t\t\t/* alert(json); */\r\n");
      out.write("\t\t\t\tvar result = eval(json);\r\n");
      out.write("\t\t\t\t/* alert(result[0].result + \":\" +result[0].desc); */\r\n");
      out.write("\t\t\t\tif (result[0].result == \"ok\") {\r\n");
      out.write("\t\t\t\t\talert(\"정상 수정 완료\");\r\n");
      out.write("\t\t\t\t\twindow.location.replace(\"A06ModifyResult.jsp\");\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\talert(result[0].desc);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

	id = (String)session.getAttribute("id");

	String query = "select *from member where id = '" + id + "'";
	
	Class.forName(driver);
	con = DriverManager.getConnection(url, uid, upw);
	stmt = con.createStatement();
	resultSet = stmt.executeQuery(query);
	
	String phone = "";
	
	while(resultSet.next()){
		name = resultSet.getString("name");
		pw = resultSet.getString("pw");
		phone = resultSet.getString("phone");
		gender = resultSet.getString("gender");
	}
	
	phone1 = phone.substring(0, 3);
	phone2 = phone.substring(4, 8);
	phone3 = phone.substring(9, 13);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<form id=\"ModifyProcess\">\r\n");
      out.write("\t아이디 : ");
      out.print(id );
      out.write("<br>\r\n");
      out.write("\t비밀번호 : <input type=\"text\" name=\"pw\" size=\"10\">\r\n");
      out.write("\t이름 :  <input type=\"text\" name=\"name\" size=\"10\" value=");
      out.print(name );
      out.write("><br>\r\n");
      out.write("\t전화번호 : <select name=\"phone1\">\r\n");
      out.write("\t\t<option value=\"010\">010</option>\r\n");
      out.write("\t\t<option value=\"016\">016</option>\r\n");
      out.write("\t\t<option value=\"017\">017</option>\r\n");
      out.write("\t\t<option value=\"018\">018</option>\r\n");
      out.write("\t\t<option value=\"019\">019</option>\r\n");
      out.write("\t\t<option value=\"011\">011</option>\r\n");
      out.write("\t</select> - \r\n");
      out.write("\t<input type=\"text\" name=\"phone2\" size=\"5\" value=");
      out.print(phone2 );
      out.write("> - \r\n");
      out.write("\t<input type=\"text\" name=\"phone3\" size=\"5\" value=");
      out.print(phone3 );
      out.write("><br>\r\n");
      out.write("\t\r\n");
      out.write("\t");

		if(gender.equals("man")){
	
      out.write("\r\n");
      out.write("\t성별구분 : <input type=\"radio\" name=\"gender\" value=\"man\" checked=\"checked\">남자 &nbsp;\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"woman\">여자<br>\r\n");
      out.write("\t");

		}else{
	
      out.write("\r\n");
      out.write("\t성별구분 : <input type=\"radio\" name=\"gender\" value=\"man\">남자 &nbsp;\r\n");
      out.write("\t\t\t<input type=\"radio\" name=\"gender\" value=\"woman\" checked=\"checked\">여자<br>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t<input type=\"button\" value=\"정보수정\" onclick=\"form_check()\">\r\n");
      out.write("\t\r\n");
      out.write("</form>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
